load("@rules_python//python:defs.bzl", "py_library")

package(default_visibility = ["//periodic_distribution_shift:__subpackages__"])

licenses(["notice"])

py_library(
    name = "dual_branch_resnet_models",
    srcs = ["dual_branch_resnet_models.py"],
)

py_library(
    name = "keras_utils_dual_branch_kmeans",
    srcs = ["keras_utils_dual_branch_kmeans.py"],
)

py_library(
    name = "keras_utils_dual_branch_kmeans_lm",
    srcs = ["keras_utils_dual_branch_kmeans_lm.py"],
)
