# Test data for MovieLens matrix factorization. Has the same format as the MovieLens 1M dataset.
# Permalink: https://grouplens.org/datasets/movielens/1m/

licenses(["notice"])

package(default_visibility = ["//reconstruction/shared:__pkg__"])

filegroup(
    name = "movielens_small",
    srcs = glob(["*.dat"]),
)
